name: Build and Deploy

on:
  push:
    branches:
      - master  # Możesz zmienić to na nazwę swojego głównego brancha

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build JSP to HTML
        uses: einaregilsson/jspc@v1

      - name: Copy HTML files
        run: |
          mkdir -p dist
          cp -R target/*.html dist/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
